### ISSUE TITLE
Problems with / ToDo for  MC 1.7

### ISSUE THREAD

**Issue by davboecki** [RS485/LogisticsPipes#419]
- [x] Fix Gate GUI.
- [x] Routing Table Laser.
- [x] Move to the new BC power system (Maybe not (Probably should still be supported as a power supplier target))
- [x] RequestTable Crafting tree isn't shown.
- [x] Gates don't receive redstone signal.
- [x] Check all API's
- [x] Disable itemConduit integration. (Untill they are released for MC1.7)
- [x] Fix LP Debug command.
- [x] Remove upgrade manager and Network manager for the pipe controller.
- [x] Check LP Trigger
- [x] Make Recipe registration more dynamic for TE and BC recipes at the same time.
- [x] Check LP's BC event handler hook.
- [x] Check security station pipe destroy blocking.
- [x] Security Station player list doesn't work.
- [ ] Fix Security Staion permissions for new Pipe controller.
- [x] Fix Security Station deauthorisation sec card removing.
- [x] ThermalExpansion Tesseracts don't work as connection (Add power transfer).

**Comment by Turmfalke2** [comment]
- [x] 
  == Items without valid destination disappear ==

<turmfalke: http://ibin.co/1W1I31SW0h4o this is my setup
<turmfalke: the basic pipe next to the chest is configured to only accept chests
<ArtForz: who the hell thought that'd make any sense is beyond me.
<turmfalke: if I now throw a stack of engines or such in the chest on the right
<turmfalke: they all slowly go to the basic pipe and then disappear
<ArtForz: that's so far normal
<turmfalke: while doing that the basic pipe starts to sparkle
<ArtForz: (they get buffered and retry for 5*2 sec or so)
<turmfalke: a few seconds after the last of the 64 items entered the pipe and disappeared it pops out one item
<turmfalke: and then the sparkling stops
<ArtForz: yeah, that's a bug.
<turmfalke: the result is 63 items got lost

**Comment by Turmfalke2** [comment]
- [x] fatal error up on spawning in Itemsink modules
  http://pastebin.com/A0j6dnNj

**Comment by sircrimer** [comment]
- [x] Itemsink module is not editable while in a mk1 chassis (probably all modules), if configured in hand, 
- [x] items do not get routed to attached inventory.

**Comment by asiekierka** [comment]
Moving to the new BC power system is a horrid idea that will slow down the mod, especially as compatibility with the old one is kept.

**Comment by sircrimer** [comment]
- [x] Logistics Request Table does not show the product of a recipe. After closing and reopening the gui the product is displayed. When the empty space is clicked, the game crashes. http://pastebin.com/GLjAEkj4
  (2 plank = 4 stick)

**Comment by sircrimer** [comment]
- [x] After placing a "fluid container supplier pipe" next to a "basic fluid pipe" (set to water, connected to an empty BC tank) the game crashed. http://pastebin.com/s4jBrQij http://imgur.com/xRAtM2R

**Comment by davboecki** [comment]
@sircrimer Did you have any recipe remover installed when you tried to use the request table and crashed? I can't reproduce the crafting client/server sync problem, but I fixed the crash.
And could you retest the "Items get not routed to it. I can't reproduce that either."

**Comment by sircrimer** [comment]
I dont have a recipe remover installed.  The Item routing was my fault.

about the sync problem: 
1. the inventory of the request table has to be empty
2. paint 2 wood planks in the request table, product stays empty
3. request 2 wood planks from the network
4. click on the empty product field
5. game crash

**Comment by bziemons** [comment]
Please keep this issue free from spam about 1.7 - It is meant to be a discussion/bug report/ToDo collection until we release our first builds via Jenkins.

**Comment by TurtleGalaxis** [comment]
someone above said not to move to the "new" buildcraft power system because it will slow down the mod. i agree, get a 1.7 release and THEN move to the new buildcraft power. i couldn't live without my builder and architect table.

**Comment by asiekierka** [comment]
No, don't move to it unless absolutely necessary. BuildCraft 5.x, 6.0.x and 6.1.x all keep full compatibility with the old and new API (and they probably will forever because RailCraft has outright refused to move to the new API).

The new API is also, in my opinion, a lot messier to deal with if you want anything beyond an internal battery represented by a double. That's also what makes it exist - it being an internal battery represented by a double makes it much easier for developers to add compatibility, but much harder to do more complex things with than the old API.

**Comment by davboecki** [comment]
LP now supports both the old and the new BC power system in both ways. To accept power with the Power Junction and the Power Provider. And it can supply to both the new BC power system and the old one. And It will probably stay that way untill BC removes the old Power API.
https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/proxy/buildcraft/BuildCraftProxy.java#L1084
https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/blocks/powertile/LogisticsBCPowerProviderTileEntity.java#L30
https://github.com/RS485/LogisticsPipes/blob/mc17/common/logisticspipes/blocks/powertile/LogisticsPowerJunctionTileEntity.java#L65

**Comment by bziemons** [comment]
@davboecki can you have a look at open tasks in here again and see if they still apply?
